# Generated by Django 2.2.16 on 2020-12-17 12:11

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file
import todo.models
import todo.storage


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0012_file_mime_type'),
        ('todo', '0011_auto_20190724_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='filer_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(max_length=255, storage=todo.storage.PrivateFileSystemStorage(), upload_to=todo.models.get_attachment_upload_dir),
        ),
    ]
