# Generated by Django 2.2.16 on 2021-01-12 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_filed_verbose_names_20210112_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_scaffold',
            field=models.BooleanField(default=False, verbose_name='is scaffold'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='is_scaffold',
            field=models.BooleanField(default=False, verbose_name='is scaffold'),
        ),
    ]
