# Generated by Django 2.2.16 on 2021-01-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20210118_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['procedure_uuid', 'priority', 'created_date']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_scaffold',
        ),
    ]
