# Generated by Django 2.2.16 on 2021-01-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='respects_priority',
            field=models.BooleanField(default=False, verbose_name='respects priority'),
        ),
    ]
